### ISSUE TITLE
Empty statements should be removed

### ISSUE THREAD

**Issue by marcosstefani** [DaveLRB/D-Dproject#51]
https://github.com/DaveLRB/D-Dproject/blob/4fd6b616aaa3cf7d243d2239efe37419002318d1/D_DProject/src/Character.java#L238

Empty statements represented by a semicolon ; are statements that do not perform any operation. They are often the result of a typo or a misunderstanding of the language syntax. It is a good practice to remove empty statements since they don’t add value and lead to confusion and errors.

**Comment by DaveLRB** [comment]
Thank you! Removed!
